### ISSUE TITLE
Roadmap and planned upgrades

### ISSUE THREAD

**Issue by zackcote** [zackcote/zackcote.github.io#1]
So the site's been up about a week now, and I've learned a couple of things. Most significantly, I hate **off-center single-column text layouts**. 

- [x] Center post content
- [x] Switch to a full-width design
- [x] **Sweden Sans** is a cool sans-serif, but doesn't have enough weights. Upgrade typography.
- [x] Implement animations that *make sense* and *have context*
- [ ] **Content Rules**: fix all case studies to have more information
- [x] Full width images, please!

Once all of this is done, I'll probably turn the 'redesign process' into a blog post. Let's go! :heart_eyes_cat:

**Comment by zackcote** [comment]
It's getting there! So far so good.

**Comment by zackcote** [comment]
More to do:

- [ ] spacing under post headers. 
- [ ] mobile padding on blog page.
